### ISSUE TITLE
To do for basic meta viewer

### ISSUE THREAD

**Issue by nycz** [nycz/sapfo#34]
**General functionality:**
- [x] Customizable page names
- [x] Save/load
- [x] Failsafe OR autocreation when there isn't a metadirectory
- [x] Create new meta pages
- [x] Remove meta pages?
- [x] Terminal
- [x] Go back to index frame
- [x] Hotkey to switch between terminal and textarea
- [x] Command to show a page's filename

**Full styling support:**
- [x] Textedit font family/size
- [x] Header size options
- [x] Color options for the different formats?
- [x] Page width
- [x] Fixed indent width

Blah blah ideas
-------
Metadata on the first line of the page files?
