### ISSUE TITLE
Tier 2 todo for meta viewer

### ISSUE THREAD

**Issue by nycz** [nycz/sapfo#35]
- [x] Sort pages after title, not file name
- [x] Autosave after page change/quit etc
- [x] Clean up the code
- [x] Customizable hotkeys
- [x] Show info about meta pages in index frame (how many, etc)
- [x] Save scrollbar and cursor position on individual pages when switching pages
- [x] Custom default name for pages created when no metadirectory exists
- [x] Better selection color
- [x] Script to convert from ZIm
- [x] Add creation date to pages' properties
- [ ] ~~Custom fonts for formats~~
- [x] Add options for automatic title when creating a new page, somehow
- [x] Add underline to formats
- [x] Fix Ctrl+S (change `save_page` to `cmd_save_current_page`)
- [x] Add word count command (like c in kalpana)
- [x] Hotkey to go back from backstoryview to indexview
